apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alert2snow-agent.fullname" . }}
  labels:
    {{- include "alert2snow-agent.labels" . | nindent 4 }}
type: Opaque
data:
  SERVICENOW_USERNAME: {{ .Values.servicenow.username | b64enc | quote }}
  SERVICENOW_PASSWORD: {{ .Values.servicenow.password | b64enc | quote }}
